simple client filtering on list_jobs
microsoft/qdk-python pull request #65
Opened 2021-05-25 21:39 UTC by adelebai

2021-06-07 19:22 UTC, sanjgupt approved these changes

2021-06-07 19:41 UTC, vxfield commented
I added @guenp as a reviewer since she is back as co-owner of the Azure Quantum SDK for Python.
Please wait for her review before merging this.

2021-06-11 20:01 UTC, guenp requested changes

2021-06-11 20:01 UTC, guenp commented on azure-quantum/azure/quantum/job.py
> +               return False
```suggestion
        if name_match is not None and re.search(name_match, self.details.name) is None:
           return False
```

2021-06-11 20:01 UTC, guenp commented on azure-quantum/azure/quantum/job.py
> +                return False
```suggestion
        if status is not None and self.details.status != status.value:
            return False
```

2021-06-11 20:01 UTC, guenp commented on azure-quantum/azure/quantum/job.py
> +                return False
```suggestion
        if created_after is not None and self.details.creation_time < created_after:
            return False
```

2021-06-11 20:01 UTC, guenp commented on azure-quantum/azure/quantum/workspace.py
> +            todo #27664 - tag filtering when swagger is ready
I would recommend not putting todo's in the code but instead track them in ADO and link this file there

2021-06-16 20:58 UTC, guenp approved these changes

2021-06-22 19:55 UTC, merged